<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DotnetFastFormat.Tests" />
    <ProjectReference Include="../../tests/DotnetFastFormat.Corpus/DotnetFastFormat.Corpus.csproj" />
    <ProjectReference Include="../../src/DotnetFastFormat.Cli/DotnetFastFormat.Cli.csproj" />
  </ItemGroup>
</Project>
